### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [OPENER-next/OpenStop#224] opened 2023-11-29 07:42 UTC
### Problem

https://gitlab.com/fdroid/fdroiddata/-/jobs/5636228675

The libflutter.so files are different, which generally means that we used different flutter version. We use the version defind in pubspec.yml. Is that changed?

### Which app version do you use?

0.6.0

### What operating system do you use?

Android

**Comment by licaon-kter** [comment] 2023-11-29 10:01
> The libflutter.so files are different

Interesting that `libapp.so` is not different :+1:

**Comment by Robbendebiene** [comment] 2023-11-30 09:25
Thanks for the report.

> The libflutter.so files are different, which generally means that we used different flutter version. We use the version defind in pubspec.yml. Is that changed?

No this hasn't changed. See:

https://github.com/OPENER-next/OpenStop/blob/245b59d3c70a570e24f4c6617e5f097d837f22a3/.github/actions/environment_setup/action.yml#L16-L27

For `flutter --version` **our** build logged:
```
Flutter 3.13.4-0.0.pre.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0daa737b7 (3 months ago) • 2023-09-12 17:01:41 -0700
Engine • revision 17a711a776
Tools • Dart 3.1.1 • DevTools 2.25.0
```


Unfortunately this call is missing in the F-Droid build script.  But when I run this locally
```
git clone --depth 1 --branch 3.13.3 https://github.com/flutter/flutter.git
flutter --version`
```
I get
```
Flutter 3.13.3 • channel [user-branch] • unknown source
Framework • revision 2524052335 (vor 3 Monaten) • 2023-09-06 14:32:31 -0700
Engine • revision b8d35810e9
Tools • Dart 3.1.1 • DevTools 2.25.0
```

So for some reason we end up with 2 different flutter versions.

I suspect the [subosito/flutter-action@v2](https://github.com/marketplace/actions/flutter-action) action. But before going further @licaon-kter @linsui can you please add  `flutter --version` to https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.tu_chemnitz.etit.sse.openstop.yml#L152-161 so we can verify this better?

**Comment by Robbendebiene** [comment] 2023-11-30 09:48
> You can see the command the recipe uses to get the right Flutter version in line https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.tu_chemnitz.etit.sse.openstop.yml#L141 what if you run it too, what do you get?
> Maybe that line needs a new updated command that extracts the version?

We also get `3.13.3` so I don't think there is anything wrong with the version extraction.

**Comment by linsui** [comment] 2023-11-30 09:49
So the problem is that you should use 3.13.3 but somehow 3.13.4-0.0.pre.2 is used.

**Comment by Robbendebiene** [comment] 2023-11-30 10:43
So we found the cause.

The Github action we use normally downloads flutter not from Github but from the flutter archive, in this case: https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.3-stable.tar.xz
Note the correct release version in the URL. However if you actually run `bin/flutter --version` inside the archive it returns `3.13.4-0.0.pre.2`.

Someone @flutter must have messed something up: 

![grafik](https://github.com/OPENER-next/OpenStop/assets/13716661/90eada33-1886-4b46-a11e-c1915c876dd1)
source: https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json
_____________
Conclusion: We changed it in #225 and will make a new release.

**Comment by licaon-kter** [comment] 2024-06-20 19:18
can you reopen?

I see https://gitlab.com/fdroid/fdroiddata/-/jobs/7145399969#L454

So I replace python-yq with `yq`, no biggie...


but then I build and: [stop080.log](https://github.com/user-attachments/files/15919170/stop080.log)

it's not repro? :(

**Comment by a-andre** [comment] 2024-06-21 06:54
@licaon-kter Have you tried `pip3 install --break-system-packages yq`?

**Comment by licaon-kter** [comment] 2024-06-21 10:54
No, wow, is there such a big diffrence in operation between yq and python-yq?

**Comment by a-andre** [comment] 2024-06-21 15:43
If I remember right, there was a problem with older versions of yq, but that seems to be solved. `yq` and `python-yq` create the same `pubspec.yaml` now.

> https://gitlab.com/fdroid/fdroiddata/-/commit/53115053bc3f71688e518945c976265137399d14

With `pip3 install` removed, `python3-pip` is no longer needed. `jq` can also be removed, because it will be installed as a dependency of `yq`.

**Comment by 7h30n3** [comment] 2024-06-24 08:55
@licaon-kter We have found out that the mismatch between the used Java versions caused the issue. We will update our build script for the GitHub action to use Java 17 and release a new version.

**Comment by licaon-kter** [comment] 2024-08-30 10:18
can you reopen? https://gitlab.com/fdroid/fdroiddata/-/jobs/7696771422#L1068

this looks like https://gitlab.com/fdroid/fdroiddata/-/issues/3299

so I applied [the fix](https://github.com/obfusk/apksigcopier#what-about-signatures-made-by-apksigner-from-build-tools--3500-rc1) locally but still
```
==== detail begin ====
verification of APK with copied signature failed
Comparing reference APK to APK with copied signature...
Unexpected diff output:
==== detail end ====
```
and
```
$ apksigcopier compare OpenStop_fdroid_v0.8.2.apk --unsigned de.tu_chemnitz.etit.sse.openstop_21.apk
Error: Unexpected metadata.
```

ok, for a test @7h30n3 @a-andre can you get an unsigned APK and sign it with `--alignment-preserved true` added here https://github.com/OPENER-next/OpenStop/blob/master/.github/workflows/build_app.yml#L94 ?

**Comment by 7h30n3** [comment] 2024-09-02 11:33
Hi @licaon-kter as requested I added the line to the build yaml and ran the github action again.
You can find the apk here: https://tuc.cloud/index.php/s/wT8FGKRPGtpXqa3

**Comment by licaon-kter** [comment] 2024-09-04 16:15
@7h30n3 same issue, next thing to test, can you get an unsigned APK and sign it with apksigner from build-tools 34?

**Comment by 7h30n3** [comment] 2024-09-05 09:52
@licaon-kter I have a new build for you signed with apksigner from build-tools version 34:

https://tuc.cloud/index.php/s/y8e2QMHJQRnx62r

**Comment by licaon-kter** [comment] 2024-09-05 13:45
Interestingly, local apksigcopier checking still failed for this one too

So I tried normal builds for your last 2 attached APKs, and looks like _"with apksigner from build-tools version 34"_ is fine, but also _"signed with `--alignment-preserved true`"_ is fine too

**Comment by 7h30n3** [comment] 2024-09-06 07:17
Sorry, I quite don't understand what this means for the way forward.

**Comment by licaon-kter** [comment] 2024-09-06 09:48
The way forward appears to be, as https://github.com/obfusk/apksigcopier#what-about-signatures-made-by-apksigner-from-build-tools--3500-rc1 explains, sign with  `--alignment-preserved true` added here https://github.com/OPENER-next/OpenStop/blob/master/.github/workflows/build_app.yml#L94

**Comment by 7h30n3** [comment] 2024-09-06 10:08
Okay, I can add this line again like it was in the first apk I send you (https://github.com/OPENER-next/OpenStop/commit/6f491bc900af3ed12f522b789a04a97ca1d5c12e).
Does this mean there needs the be fixed something on the side of F-Droid or how do we get reproducable builds working again?

**Comment by licaon-kter** [comment] 2024-09-06 10:18
You can replace the APK in https://github.com/OPENER-next/OpenStop/releases/tag/v0.8.2 with the fixed one and we can reenable this version.

**Comment by 7h30n3** [comment] 2024-09-06 12:03
I added a "new version" for `OpenStop_fdroid_v0.8.2.apk` to the 0.8.2 release. You can reenable the version in F-Droid. Fingers crossed that it will work.

**Comment by licaon-kter** [comment] 2024-09-06 12:39
thanks https://gitlab.com/fdroid/fdroiddata/-/commit/93f36d7869ef915dc9d6e5ec5af86836e3fc0be3

/close this

**Closed** 2024-09-06 12:56 UTC

**Comment by linsui** [comment] 2025-01-08 07:39
There is no release for 0.8.3. Could you please upload the apk?

**Comment by 7h30n3** [comment] 2025-01-08 10:21
The release is still in draft. We only need to add the release notes.
We had some issues with the iOS build.
